service: ServerlessTutorial_1_HelloWorld

frameworkVersion: ">=1.2.0"

provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    # Allows Lambda to download and upload files to S3 bucket
    - Effect: Allow
      Action:
        - 's3:ListBucket'
      Resource: 'arn:aws:s3:::${env:S3BucketName}'
    - Effect: Allow
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
      Resource: 'arn:aws:s3:::${env:S3BucketName}/*'

package:
  exclude:
    - node_modules/**

functions:
  HelloWorld:
    handler: index.handler
    events:
      - http:
          path: hello
          method: get

